[package]
name = "telemetry-consumer"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "telemetry-consumer"
path = "src/main.rs"

[dependencies]
telemetry-core = { workspace = true, features = ["production"] }
telemetry-proto = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
dotenvy = { workspace = true }
clap = { workspace = true }
